server:
  port: 520

# 注册Eureka服务
eureka:
  instance:
    # 服务注册中心实例的主机名
    hostname: localhost
  client:
    # Eureka服务注册中心会将自己作为客户端来尝试注册它自己，必須禁止
    register-with-eureka: false
    fetch-registry: false
    # 服务注册中心的配置内容，指定服务注册中心的位置
    service-url:
      #defaultZone: http://@${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      # 关闭自我保护
      enable-self-preservation: false
      # 清理无效节点的时间间隔（单位毫秒，默认是60*1000）
      eviction-interval-timer-in-ms: 30000
spring:
  application:
    name: eureka-server
